name: .NET Core Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x      # current LTS
        cache: false               # disable built-in NuGet cache to avoid lock file issues
    - name: Restore dependencies
      run: dotnet restore /p:RestoreLockedMode=false
    - name: Build
      run: dotnet build -bl:build.binlog --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Upload build logs on failure
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ github.run_id }}
        path: |
          **/*.binlog
          **/bin/Release/netcoreapp*/*.txt
          **/obj/Release/netcoreapp*/*.txt
